### ISSUE TITLE
Doesn't seem to work with 1.05

### ISSUE THREAD

**Issue by chetan-prime** [DivanteLtd/mage2vuestorefront#20]
I had vue-storefront working with 1.01 in testing. Subsequently I stopped & deleted docker-compose, and then made a fresh install of vue-storefront-api & vue-storefront.
Next I made sure all indexes are created freshly & then tried to import freshly all data from magento. I am able to successfully import categories, attributes etc. , but I get errors when importing products. As result I am able to see categories in veu-storefront but the products list is empty.

[mage2vuestorefront.log](https://github.com/DivanteLtd/mage2vuestorefront/files/2113860/mage2vuestorefront.log)

**Comment by pkarw** [comment]
Hi there! Thanks for reporting this one it seems like your config.js doesn’t contain this line: https://github.com/DivanteLtd/mage2vuestorefront/blob/665f61686f2bddb9b2c12a5f02a2a2eb3317ee30/src/config.js#L15

I’ll fix the way m2vs reads the config because if you modified the configuration and update all other files with gut pull, but the config: that’s how it ends up :)

Sorry for a problem. After you’ll add this line to config.js it should work just fine

**Comment by chetan-prime** [comment]
Thanks for your quick feedback.
As you said I noticed my old config.js was missing some of the new additions. I have added them and with the new env vars now it now works fine, the new fullreindex feature esp. is good
